---
flighdeck_motd_name: "Tractorbeam 2.1.0"

flightdeck_groups:
  - name: "backup"

flightdeck_users:
  - name: "backup"
    group: "backup"
    groups:
      - "cron"
    home: "/home/backup"

flightdeck_root_prompt: '\u@tractorbeam:\w# '
flightdeck_user_prompt: '\u@tractorbeam:\w$ '

platformsh_cli_version: "v3.44.0"
platformsh_cli_url: "https://github.com/platformsh/platformsh-cli/releases/download/{{ platformsh_cli_version }}/platform.phar"
